### DISCUSSION TITLE
Error in github action

### DISCUSSION THREAD

**Discussion by JakeHadley** [onepub-dev/onepub#530] [Support]
What is going wrong here? This is happening in my github action to publish to onepub. The action looks like this:
```
name: Publish

on: 
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.13.8'
        
        - name: Set up onepub
          run: |
            flutter pub global activate onepub
            export ONEPUB_TOKEN="${{ secrets.ONEPUB_T }}"; onepub import
        - name: Publish to onepub
          run: | 
            dart pub publish
```
The output is this:
```
Validating package...
Publishing is forever; packages cannot be unpublished.
Policy details are available at https://pub.dev/policy
Package upload canceled.
Do you want to publish quiz_core 0.0.1+1 to https://onepub.dev/api/<endpoint>/ (y/N)? 
Error: Process completed with exit code 65.
```

**Comment by JakeHadley** [comment]
I guess I needed to give my ci/cd user an uploader role. Closing.

**Comment by bsutton** [comment]
Glad I could help:)

**Comment by bsutton** [comment]
Would you mind if I published your action as an example in the invitation
onepub documentation?

**Reply by JakeHadley** [reply]
Sure, this is what it evolved into:
```
name: Publish

on: 
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.13.8'
        
        - name: Set up onepub
          run: |
            flutter pub global activate onepub
            export ONEPUB_TOKEN="${{ secrets.ONEPUB_T }}"; onepub import
        - name: Dry run publish to onepub
          id: dryrun
          run: | 
            dart pub publish -n
        - name: Publish to onepub
          if: steps.dryrun.outcome == 'success'
          run: | 
            dart pub publish -f

```
Feel free to do with it as you will.
