### ISSUE TITLE
package > installing > dependencies formatting issue

### ISSUE THREAD

**Issue by GerhardMalan** [onepub-dev/onepub#166]
On the `installing` tab of a **_PRIVATE_** package page the section for the *dependencies* generates invalid `YAML`. _The public packages appear to generate the correct `YAML`._

To reproduce the behavior:
1. Go to "installing" tab of a **_PRIVATE_** package (e.g. "https://onepub.dev/packages/my_package/xxxxxxxxxx")
2. Copy dependencies section to your pubspec.yaml.
3. Formatting error is raised by the pasted `YAML`:
```yaml
   dependencies:
    my_package:^0.0.1-5
      hosted: https://onepub.dev/api/xxxxxxxxxx
```

**Expected behavior**
There should white-space between the ":" and the version number for the dependency as shown below:
```yaml
   dependencies:
    my_package: ^0.0.1-5
      hosted: https://onepub.dev/api/xxxxxxxxxx
```
