### ISSUE TITLE
CLI removes comments from pubspec.yaml file when calling `onepub pub private`

### ISSUE THREAD

**Issue by ahmednfwela** [onepub-dev/onepub#191]
consider this file:
```yaml
name: abcd
description: abcd
version: 1.2.3
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.8.0"
dependencies:
  flutter:
    sdk: flutter
  # commenting a temporary dependency 
  # injectable:
dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter
#this is a comment
flutter:
```
when calling `onepub pub private`, it gets transformed to:
```yaml
name: abcd
description: abcd
version: 1.2.3
publish_to: https://onepub.dev/api/xxxxxxx
environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.8.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter
flutter: null
```

notice how `flutter` is set to null, and all comments were removed
